name: 'Build and release'

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: npm

    - run: npm i
    - run: npm run build
    - run: npm run package

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ steps.package-version.outputs.current-version}}"
        title: "v${{ steps.package-version.outputs.current-version}}"
        files: |
          dist/zxgenerator-linux.gz
          dist/zxgenerator-macos.gz
          dist/zxgenerator-win.exe
