name: 'Build and release'
description: 'Build, package, and release'

on:
  push:
    branches: [ main ]

jobs:
  nodejstest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: npm
    - uses: actions/checkout@v2
    - run: npm i
    - run: npm run build
    - run: npm run package